[versions]
# Plugins
spotless = "3.0.1"

# Libraries
configurate = "4.2.0"

[libraries]
configurateCore = { group = "org.spongepowered", name = "configurate-core", version.ref = "configurate" }
configurateYaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }


[plugins]
spotless = {id = "net.kyori.indra.licenser.spotless", version.ref = "spotless"}